# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Daniel Flores" # el título del sitio web
first_name: Daniel
middle_name: I.
last_name: Flores
email: daniel.flores01@epn.edu.ec
description: > 
  Página personal de Daniel para mostrar información y proyectos.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> con <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: portafolio, página personal, proyectos, sobre mí
lang: es # el idioma de tu sitio (por ejemplo: en, fr, cn, ru, etc.)
icon: ⚛️ # el emoji utilizado como favicon

url: https://danielFe.github.io # URL base del sitio
baseurl: "" # URL del subdirectorio del sitio. Deja en blanco si está en la raíz.
back_to_top: true # mostrar botón "volver arriba"

# -----------------------------------------------------------------------------
# Navegación
# -----------------------------------------------------------------------------

nav:
  - title: "Sobre mí"
    url: /about/
  - title: "Proyectos"
    url: /projects/

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false # deshabilitar la búsqueda
socials_in_search: false

# Dimensiones
max_width: 930px

# -----------------------------------------------------------------------------
# Colecciones
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /:collection/:title/

announcements:
  enabled: false

latest_posts:
  enabled: false

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown y resaltado de sintaxis
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Incluye y excluye
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-scholar

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed
  implementation: Sass::Embedded

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false # deshabilitar google analytics
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_masonry: false
enable_math: false
enable_tooltips: false
enable_darkmode: true # habilitar modos oscuro/claro
enable_navbar_social: false
enable_project_categories: false
enable_medium_zoom: false
enable_progressbar: false
enable_video_embedding: false

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js", "assets/libs/**/*"]
  uglifier_args:
    harmony: true

scholar:
  source: _bibliography
  bibliography: references.bib
  style: apa
  locale: en
